### ISSUE TITLE
Issue on 'pytrmm' installing

### ISSUE THREAD

**Issue by mjwang1010** [sahg/pytrmm#1]
I had a problem when installing 'setup.py'. Following the steps, I just got an error below:
"
IOError: [Errno 2] No such file or directory: 'pytrmm/__dev_version.py'
"
I cannot find the reason..

**Comment by scottza** [comment]
Can you give more detail explaining exactly what you did?

I'm guessing you downloaded the source as a zip from Github, but that should install fine even if you didn't use a git checkout...

**Comment by mjwang1010** [comment]
Hi, Scottza. Yes, I downloaded the zip file and tried to install the package. I just typed the code "python setup.py install" (I replaced the "setup.py" with its local path) in the terminal line. But I got the error above at last. It also included other information on the screen:
"
.../setup.py, line 56, in <module>
    full_version, git_rev = generate_version_py(dev_version_py)
.../setup.py, line 47, in generate_version_py
    f = open(filename, "w")
"
Since I am a greenhand on Python, maybe there is something wrong with my steps? Thanks!

**Comment by scottza** [comment]
Ah, now I see your trouble.

You need to change into the top level pytrmm directory on the command line, and then run `python setup.py install` from there. Something like the following:

```
cd path/to/unzipped/package
python setup.py install
```

The trouble is that the setup is looking for files in the sub-directory pytrmm relative to your current working directory, since no such sub-directory exists, the files can't be found...

**Comment by mjwang1010** [comment]
It works! Thanks-

**Comment by scottza** [comment]
Great!
